version: event.ConcatViT  # Version of config file.
date: '2021-11-30'  # Creation date of this file.

runner: EventRunner  # Class name of executor.
recorder: EventRecorder  # Class name of recorder.
data: event  # Name of the dataset.
seed: 2021  # Random seed.

device: 'cuda:0'  # Device used to deploy model.
epochs: 100  # Total epochs of training.

# == Model ==
model: ConcatViT  # Name of model class.
model_args:  # Assignment of model parameters.
  height: 120
  width: 160
  rnn: GRU
  teacher_forcing: true
  c_pair_embed: 8
  max_step: 4
  c_hidden: [128]
  arch: 'vit_small'
  fc_img_en: [128]
  fc_fusion: [128]

# == Optimizer ==
optimizer: AdamW  # Name of optimizer class.
optimizer_args:  # Assignment of optimizer parameters.
  lr: 0.001
lr_scheduler: StepLR
lr_scheduler_args:
  step_size: 25
  gamma: 0.1

# == Evaluator ==
evaluator: EventEvaluator  # Name of optimizer class.
evaluator_args:  # Assignment of optimizer parameters.
  values_json: '../data/gen_src/resource/values.json'
  properties_json: '../data/gen_src/resource/properties.json'

# == Dataset ==
data_class_default: &data_class_default Event
data_args_default: &data_args_default
  data_root: '../data/trance'
  values_json: '../data/gen_src/resource/values.json'
  properties_json: '../data/gen_src/resource/properties.json'
  img_aug: false
  move_out_aug: false
data_loader_args_default: &data_loader_args_default
  batch_size: 224
  num_workers: 12
  pin_memory: true
  shuffle: false

train_data: *data_class_default
train_data_args:
  <<: *data_args_default
  split: train
  img_aug: true
  move_out_aug: true
train_data_loader_args:
  <<: *data_loader_args_default
  shuffle: true
val_data: *data_class_default
val_data_args:
  <<: *data_args_default
  split: val
val_data_loader_args:
  <<: *data_loader_args_default
test_data: *data_class_default
test_data_args:
  <<: *data_args_default
  split: test
test_data_loader_args:
  <<: *data_loader_args_default

# == Logging ==
output_root: '../train_log/TVR'  # Location to put train logs.
log_steps: 10  # Step interval of standard output.
# (Auto changed variables)
log_dir: '../train_log/TVR/event/2021-11-30.event.ConcatViT/log'                                # Full path of log dir
ckpt_dir: '../train_log/TVR/event/2021-11-30.event.ConcatViT/ckpt'                                # Full path of checkpoint dir
tb_dir: '../train_log/TVR/event/2021-11-30.event.ConcatViT/tb'                                # Full path of tensorboard dir
result_path: '../train_log/TVR/event/2021-11-30.event.ConcatViT/result/result.json'

# == Testing Results ==
result:
  version: event.ConcatViT
  ckpt: best
  model_size: 25.4M
  time: '2021-12-03 18:20:39'
  loss: 11.045717388916016
  loss_obj: 2.282075720977783
  loss_pair: 8.76364174118042
  acc: 0.6118
  loose_acc: 0.63955
  avg_dist: 0.9222
  avg_norm_dist: 0.28719583988189695
  avg_step_diff: -0.06
  step_result:
    1:
      acc: 0.9516
      loose_acc: 0.9726
      avg_dist: 0.0426
      avg_norm_dist: 0.0426
    2:
      acc: 0.7582
      loose_acc: 0.795
      avg_dist: 0.3996
      avg_norm_dist: 0.1998
    3:
      acc: 0.4878
      loose_acc: 0.5202
      avg_dist: 1.1368
      avg_norm_dist: 0.3789333390414715
    4:
      acc: 0.2496
      loose_acc: 0.2704
      avg_dist: 2.1098
      avg_norm_dist: 0.52745
